### ISSUE TITLE
Can't run on Debian after pip install

### ISSUE THREAD

**Issue by RichiH** [MoritzR/fints2ledger#1]
I am seeing the following:

````
% pip install fints2ledger
Collecting fints2ledger
  Downloading https://files.pythonhosted.org/packages/3d/aa/0e18115ba8e2e401004ee6d16b247415fbab4fbd282fab62912204672e66/fints2ledger-0.4.2.tar.gz
Requirement already satisfied: PyYAML<4,>=3.13 in /usr/lib/python2.7/dist-packages (from fints2ledger) (3.13)
Collecting fints<3,>=2 (from fints2ledger)
  Downloading https://files.pythonhosted.org/packages/a1/77/17975b4d0cb8d6a417038e835f83a39ea061e10ade65f381ad4309b433e0/fints-2.1.1.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 454kB/s 
Collecting mt-940<5,>=4.11 (from fints2ledger)
  Downloading https://files.pythonhosted.org/packages/a6/07/5f87c6b3d87dac0e4b159939ca4683632a38fbc7ec9dd395ac95c57451c5/mt_940-4.17.0-py2.py3-none-any.whl (149kB)
    100% |████████████████████████████████| 153kB 900kB/s 
Collecting bleach (from fints<3,>=2->fints2ledger)
  Downloading https://files.pythonhosted.org/packages/ab/05/27e1466475e816d3001efb6e0a85a819be17411420494a1e602c36f8299d/bleach-3.1.0-py2.py3-none-any.whl (157kB)
    100% |████████████████████████████████| 163kB 765kB/s 
Collecting requests (from fints<3,>=2->fints2ledger)
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 681kB/s 
Collecting sepaxml==2.0.* (from fints<3,>=2->fints2ledger)
  Downloading https://files.pythonhosted.org/packages/0c/57/eced88674e5479eb8851f0a3a3193aced9b8fc4f4b43b6d48b41493fd293/sepaxml-2.0.0.tar.gz
Requirement already satisfied: enum34>=1.1.6; python_version <= "2.7" in /usr/lib/python2.7/dist-packages (from mt-940<5,>=4.11->fints2ledger) (1.1.6)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python2.7/dist-packages (from bleach->fints<3,>=2->fints2ledger) (1.12.0)
Requirement already satisfied: webencodings in /usr/lib/python2.7/dist-packages (from bleach->fints<3,>=2->fints2ledger) (0.5.1)
Collecting idna<2.9,>=2.5 (from requests->fints<3,>=2->fints2ledger)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 203kB/s 
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/dist-packages (from requests->fints<3,>=2->fints2ledger) (3.0.4)
Collecting certifi>=2017.4.17 (from requests->fints<3,>=2->fints2ledger)
  Downloading https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl (158kB)
    100% |████████████████████████████████| 163kB 658kB/s 
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->fints<3,>=2->fints2ledger)
  Downloading https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl (150kB)
    100% |████████████████████████████████| 153kB 2.5MB/s 
Building wheels for collected packages: fints2ledger, fints, sepaxml
  Running setup.py bdist_wheel for fints2ledger ... done
  Stored in directory: /home/richih/.cache/pip/wheels/1a/72/23/50c03392d3e9a8fc9268da7bb78a1cd22f14ecef154d138729
  Running setup.py bdist_wheel for fints ... done
  Stored in directory: /home/richih/.cache/pip/wheels/21/0c/8b/3ffa663443c95589a729c1eb0d66998939d604fb0a21bc9e6a
  Running setup.py bdist_wheel for sepaxml ... done
  Stored in directory: /home/richih/.cache/pip/wheels/fc/e2/01/da9790463e284b12b034d0e1c776eb8bb53bdceb171a05ea2f
Successfully built fints2ledger fints sepaxml
Installing collected packages: bleach, mt-940, idna, certifi, urllib3, requests, sepaxml, fints, fints2ledger
  The script fints2ledger is installed in '/home/richih/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed bleach-3.1.0 certifi-2019.3.9 fints-2.1.1 fints2ledger-0.4.2 idna-2.8 mt-940-4.17.0 requests-2.22.0 sepaxml-2.0.0 urllib3-1.25.3
% /home/richih/.local/bin/fints2ledger
Traceback (most recent call last):
  File "/home/richih/.local/bin/fints2ledger", line 6, in <module>
    from fints2ledger.main import main
  File "/home/richih/.local/lib/python2.7/site-packages/fints2ledger/main.py", line 2, in <module>
    from fints2ledger.fints2csv import Fints2Csv
  File "/home/richih/.local/lib/python2.7/site-packages/fints2ledger/fints2csv.py", line 2, in <module>
    from fints.client import FinTS3PinTanClient
  File "/home/richih/.local/lib/python2.7/site-packages/fints/client.py", line 57
SyntaxError: Non-ASCII character '\xc3' in file /home/richih/.local/lib/python2.7/site-packages/fints/client.py on line 58, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
%
````

**Comment by MoritzR** [comment]
Are you running this on WSL?
I have the same problem when trying this with Ubuntu on WSL, but not on a natively running Ubuntu.

**Comment by RichiH** [comment]
It's a native installation of a mix of Debian testing/unstable.

**Comment by MoritzR** [comment]
Which python version are you running?

**Comment by varac** [comment]
@RichiH Don't know if it helps you but I'm using [pipx](https://github.com/pipxproject/pipx) which works great installing fints2ledger. It uses isolated environments which might help in your case .. ?

**Comment by MoritzR** [comment]
I assume this is because the python version is below the required python version. The `fints` library seen in the error message requires at least python 3.4.

I [added a required python version](https://github.com/MoritzR/fints2ledger/commit/bd8cc376e4279cb98f74e6fcd8db382f3d273c55) to `setup.py`.
It now shouldn't let you install the newest version of the program on older python versions.

Please try again with python >=3.5. Also let me know if there is anything else that could be improved regarding the required python version and how it is communicated.
