### ISSUE TITLE
Handle TANs

### ISSUE THREAD

**Issue by varac** [MoritzR/fints2ledger#6]
When fetching transactions from a period over 3 month my bank request a TAN and fints2ledger fails to handle this:

```
❯ fints2ledger
You should register your program with the ZKA and pass your own product_id as a parameter.
Traceback (most recent call last):
  File "/home/varac/.local/bin/fints2ledger", line 8, in <module>
    sys.exit(main())
  File "/home/varac/.local/pipx/venvs/fints2ledger/lib/python3.8/site-packages/fints2ledger/main.py", line 9, in main
    Fints2Csv(config).retrieveAndSave()
  File "/home/varac/.local/pipx/venvs/fints2ledger/lib/python3.8/site-packages/fints2ledger/fints2csv.py", line 23, in retrieveAndSave
    csv_output = "\n".join(map(lambda transaction: converter.convert(
TypeError: 'NeedTANResponse' object is not iterable
```

It's not super important for me because I use `--date` to fetch only the last 3 month, but it would be still good if fints2ledger would support TANs for the case where you depend on getting transactions longer than this limit.

**Comment by varac** [comment]
For the record, this was discussed also in https://github.com/MoritzR/fints2ledger/issues/4#issuecomment-596755868 but I thought a dedicated issue makes most sense.

**Comment by varac** [comment]
I'm fine with a `won't-fix`, and can live pretty well with only fetching transactions from the last 3 month.
